const API = [
  {
    brand: "Nike",
    name: "Air Max 97",
    type: "sneakers",
    images: [
      "static/sepatu2.png",
      "static/sepatu3.png",
      "static/sepatu4.png",
      "static/sepatu5.png",
    ],
    price: 200,
    desc: "Since its debut nearly 25 years ago, the legendary Air Max 97 has been remixed by just about everyone who's anyone in the sneaker world, from Sean Wotherspoon to Lil Nas X. Inspired by the sleek aesthetics of Japanese bullet trains (or so the story goes), its wavy lines and formidable silhouette will sync up seamlessly with the type of big, brash pants we've been championing.",
    sizes: [36, 37, 38, 40, 37],
    sales: 1000,
  },
  {
    brand: "Nike",
    name: "Air Foamposite 1",
    type: "sneakers",
    images: ["static/sepatu6.png", "static/sepatu7.png", "static/sepatu8.png"],
    price: 350,
    desc: "Thanks, in part, to a blockbuster collaboration with Comme des Garçons, the pendulum of popular opinion is once again swinging firmly towards Foams. We're not going to say we told you so but...we told you so.",
    sizes: [41, 42, 43, 44, 35],
    sales: 900,
  },
  {
    brand: "Adidas",
    name: "Adilette Shower",
    type: "Flip flops",
    images: ["static/sendal1.png", "static/sendal2.png", "static/sendal3.png"],
    price: 3,
    desc: "Put these sandals on and you're ready to go. These slides combine 3-Stripes style with comfortable cloudfoam unitsole, combined midsole and outsole for superior cushioning. It features a striking adidas logo on the side.",
    sizes: [41, 34, 43, 44, 23],
    sales: 800,
  },
  {
    brand: "Rebook",
    name: "Run & Sports",
    type: "Lace up Shoes",
    images: [
      "static/sepatu10.png",
      "static/sepatu11.png",
      "static/sepatu12.png",
    ],
    price: 90,
    desc: "Put these sandals on and you're ready to go. These slides combine 3-Stripes style with comfortable cloudfoam unitsole, combined midsole and outsole for superior cushioning. It features a striking adidas logo on the side.",
    sizes: [41, 42, 36, 44, 34],
    sales: 700,
  },
  {
    brand: "Puma",
    name: "SoftRide Sophia Running Shoes",
    type: "sneakers",
    images: [
      "static/sepatu13.png",
      "static/sepatu14.png",
      "static/sepatu15.png",
    ],
    price: 65,
    desc: "Soft sneaks with an edge. SoftRide Sophia comes with SoftRide foam and SoftFoam+ to keep you comfy while you make a running session",
    sizes: [35, 36, 37, 38, 40],
    sales: 600,
  },
  {
    brand: "Nike",
    name: "Airmax 90 sliders",
    type: "sneakers",
    images: ["static/sendal4.png", "static/sendal5.png", "static/sendal6.png"],
    price: 75,
    desc: "The Nike Air Max 90 Slide honours the legendary shoe that shook up the sneaker scene 30 years ago. The visible Max Air unit in the heel celebrates its strong heritage, while colourful stitched-in TPU elements add retro styling. The foam footbed and plush strap lining offer comfort and support. An embroidered Swoosh and premium materials elevate this slide into a category all its own.",
    sizes: [44, 42, 41, 38, 40],
    sales: 500,
  },
  {
    brand: "Adidas",
    name: "Superstar shoes",
    type: "sneakers",
    images: [
      "static/sepatu16.png",
      "static/sepatu17.png",
      "static/sepatu18.png",
    ],
    price: 173,
    desc: "There’s no wrong way to wear adidas Superstar shoes. The timeless design works in any setting, from classic white with black stripes to eye-catching all-over patterns and iridescent colors.",
    sizes: [35, 36, 37, 38, 40, 41, 42, 43],
    sales: 900,
  },
  {
    brand: "Rebook",
    name: "Club C 85",
    type: "sneakers",
    images: [
      "static/sepatu19.png",
      "static/sepatu20.png",
      "static/sepatu21.png",
    ],
    price: 85,
    desc: "Smooth is how you roll. Now, you have the kicks to match. Slip on these Club C 85 sneakers and hit the scene. A simple style means these supple leather shoes pair up with anything. Because sometimes you don't have to say anything to make a statement.",
    sizes: [35, 37, 38, 40, 43],
    sales: 600,
  },
  {
    brand: "Adidas",
    name: "Yeezy powerphase calabasas",
    type: "sneakers",
    images: [
      "static/sepatu22.png",
      "static/sepatu23.png",
      "static/sepatu24.png",
    ],
    price: 175,
    desc: "Revived from the adidas archives, the Yeezy Powerphase blends simplicity with sophistication.",
    sizes: [40, 41, 42, 43],
    sales: 900,
  },
  {
    brand: "Puma",
    name: "Match 74 Lace-Up Fashion",
    type: "Lace up Shoes",
    images: [
      "static/sepatu25.png",
      "static/sepatu26.png",
      "static/sepatu27.png",
    ],
    price: 110,
    desc: "Taking cues from puma iconic 'match' from the 1974 tennis collection, the match stays true to a simplistic, yet classic approach to a tennis shoe. The match 74 citi series features a burnished leather upper and the extra lateral reinforcement that tennis players need on their shoes.",
    sizes: [35, 42, 43],
    sales: 400,
  },
  {
    brand: "Adidas",
    name: "Pharrell NMD Hu",
    type: "sneakers",
    images: [
      "static/sepatu28.png",
      "static/sepatu29.png",
      "static/sepatu30.png",
    ],
    price: 250,
    desc: "The adidas Originals x Pharrell Williams collaboration is an extension of Pharrell’s vision to meld fashion, design and functionality to create quality everyday staples.",
    sizes: [39, 40, 41, 42, 43],
    sales: 800,
  },
  {
    brand: "Nike",
    name: "Dunk High Retro",
    type: "sneakers",
    images: [
      "static/sepatu31.png",
      "static/sepatu32.png",
      "static/sepatu33.png",
    ],
    price: 180,
    desc: "The Nike Dunk High is the iconic model of sneakers loved by many sports enthusiasts. Strap your feet into the latest high-top sneaks on the market. Say goodbye to weak construction and sore feet with these shoes that are built to do battle. Slip these on for a more fulfilling experience at work or play",
    sizes: [36, 37, 42, 43, 49],
    sales: 900,
  },
  {
    brand: "Rebook",
    name: "Beatnik sandals",
    type: "Flip flops",
    images: ["static/sendal7.png", "static/sendal8.png", "static/sendal9.png"],
    price: 160,
    desc: "Go for that bohemian poet vibe. These slip-on sandals have a low-key look. Saturated color from upper to outsole gives them a minimalist look. Deep ridges on the outsole create a fierce profile and add traction.",
    sizes: [35, 42, 48, 47],
    sales: 400,
  },
];

export default API;
